export interface Rachkarn {
  prefixth: string;
  firstnameth: string;
  lastnameth: string;
  nickname: string;
  prefixen: string;
  firstname_en: string;
  lastname_en: string;
  position: string;
  birthdayme: string;
  religion: string;
  cardnumber: string;
  blood: string;

  numberhouse: string;
  village: string;
  villagename: string;
  alley: string;
  road: string;
  tambon: string;
  amphure: string;
  province: string;
  zipcode: string;
  telephone: string;
  telephonemobile: string;
  emailme: string;

  fnumberhouse: string;
  fvillage: string;
  fvillagename: string;
  falley: string;
  froad: string;
  ftambon: string;
  famphure: string;
  fprovince: string;
  fzipcode: string;
  ftelephone: string;
  ftelephonemobile: string;
  femail: string;

  status: string;
  spousename: string;
  spouselastname: string;
  spouseoldlastname: string;
  spouseage: string;
  spousereligion: string;
  spouseoccupation: string;
  spouseoccupationwork: string;
  spouseworkprovince: string;
  spousetelephone: string;

  fathername: string;
  fatherlastname: string;
  fatherbirthday: string;
  fatherreligion: string;
  fatherage: string;
  fathernumberhouse: string;
  fathervillage: string;
  fathervillagename: string;
  fatheralley: string;
  fatherroad: string;
  fathertambon: string;
  fatheramphure: string;
  fatherprovince: string;
  fatherzipcode: string;
  fathertelephone: string;
  fathertelephonemobile: string;

  mothername: string;
  motherlastname: string;
  motherbirthday: string;
  motherreligion: string;
  motherage: string;
  mothernumberhouse: string;
  mothervillage: string;
  mothervillagename: string;
  motheralley: string;
  motherroad: string;
  mothertambon: string;
  motheramphure: string;
  motherprovince: string;
  motherzipcode: string;
  mothertelephone: string;
  mothertelephonemobile: string;

  datelaisen: string;
  monthlaisen: string;
  yearlaisen: string;
}
